//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 07:49:02 PM EEST 
//


package mse.difftab.config;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="sourceDb">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="table" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="query" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="column" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="nameFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                     &lt;attribute name="secondaryKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                     &lt;attribute name="compare" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="nameFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="schemaFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="rows" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *                           &lt;attribute name="compare" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                           &lt;attribute name="groupByKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *                 &lt;attribute name="connectionUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="schema" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="preferredKey" default="PK">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="ROWID"/>
 *                       &lt;enumeration value="PK"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sourcePrepared">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="action" default="COMPARE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="COMPARE"/>
 *             &lt;enumeration value="COMPARE_KEEP_FILES"/>
 *             &lt;enumeration value="PREPARE_FILES_NOSORT"/>
 *             &lt;enumeration value="PREPARE_FILES_SORT"/>
 *             &lt;enumeration value="DISPLAY_CHECK_SUM"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="groupByKey" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="displayCheckSum" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="idCharset" type="{http://www.w3.org/2001/XMLSchema}string" default="ISO-8859-15" />
 *       &lt;attribute name="dateFormat" type="{http://www.w3.org/2001/XMLSchema}string" default="dd.MM.yyyy" />
 *       &lt;attribute name="timestampFormat" type="{http://www.w3.org/2001/XMLSchema}string" default="dd.MM.yyyy HH:mm:ss.SSSSSSSSS" />
 *       &lt;attribute name="timeFormat" type="{http://www.w3.org/2001/XMLSchema}string" default="HH:mm:ss.SSSSSSSSS" />
 *       &lt;attribute name="rows" default="1000000">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="9223372036854775807"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="loggedMismatchesMax" default="9223372036854775807">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="9223372036854775807"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="maxKeyColSize" default="255">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="32767"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="hashMethod" default="MD5">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="MD5"/>
 *             &lt;enumeration value="SHA-1"/>
 *             &lt;enumeration value="SHA-256"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="queueChunkSize" default="1000">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="1000000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="parallelDegree" default="8">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="hashBuilderQueueSizePerSource" default="2">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="100"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="logColumnSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default=";" />
 *       &lt;attribute name="logKeyValueSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="," />
 *       &lt;attribute name="logKeyValueEnclosedBy" type="{http://www.w3.org/2001/XMLSchema}string" default=""" />
 *       &lt;attribute name="logPrintHeader" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="OverallColumnName" type="{http://www.w3.org/2001/XMLSchema}string" default="THE_REST_OF_THE_COLUMNS" />
 *       &lt;attribute name="NoSuchColumnIndicator" type="{http://www.w3.org/2001/XMLSchema}string" default="_NSC_" />
 *       &lt;attribute name="NullValueIndicator" type="{http://www.w3.org/2001/XMLSchema}string" default="_NULL_" />
 *       &lt;attribute name="NoDataSerializerIndicator" type="{http://www.w3.org/2001/XMLSchema}string" default="_NDS_" />
 *       &lt;attribute name="TreatNoSuchColumnAsNull" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="TreatEmptyAsNull" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="NullIsTypeless" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="scope" default="SCHEMA_SELECTED">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="SCHEMA_COMMON"/>
 *             &lt;enumeration value="SCHEMA_SELECTED"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="numberOfHashFiles">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NestedElementSepator" type="{http://www.w3.org/2001/XMLSchema}string" default="." />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceDbOrSourcePrepared"
})
@XmlRootElement(name = "config")
public class Config {

    @XmlElements({
        @XmlElement(name = "sourceDb", type = Config.SourceDb.class),
        @XmlElement(name = "sourcePrepared", type = Config.SourcePrepared.class)
    })
    protected List<Object> sourceDbOrSourcePrepared;
    @XmlAttribute(name = "action")
    protected String action;
    @XmlAttribute(name = "groupByKey")
    protected Boolean groupByKey;
    @XmlAttribute(name = "displayCheckSum")
    protected Boolean displayCheckSum;
    @XmlAttribute(name = "idCharset")
    protected String idCharset;
    @XmlAttribute(name = "dateFormat")
    protected String dateFormat;
    @XmlAttribute(name = "timestampFormat")
    protected String timestampFormat;
    @XmlAttribute(name = "timeFormat")
    protected String timeFormat;
    @XmlAttribute(name = "rows")
    protected Long rows;
    @XmlAttribute(name = "loggedMismatchesMax")
    protected Long loggedMismatchesMax;
    @XmlAttribute(name = "maxKeyColSize")
    protected Integer maxKeyColSize;
    @XmlAttribute(name = "hashMethod")
    protected String hashMethod;
    @XmlAttribute(name = "queueChunkSize")
    protected Integer queueChunkSize;
    @XmlAttribute(name = "parallelDegree")
    protected Integer parallelDegree;
    @XmlAttribute(name = "hashBuilderQueueSizePerSource")
    protected Integer hashBuilderQueueSizePerSource;
    @XmlAttribute(name = "logColumnSeparator")
    protected String logColumnSeparator;
    @XmlAttribute(name = "logKeyValueSeparator")
    protected String logKeyValueSeparator;
    @XmlAttribute(name = "logKeyValueEnclosedBy")
    protected String logKeyValueEnclosedBy;
    @XmlAttribute(name = "logPrintHeader")
    protected Boolean logPrintHeader;
    @XmlAttribute(name = "OverallColumnName")
    protected String overallColumnName;
    @XmlAttribute(name = "NoSuchColumnIndicator")
    protected String noSuchColumnIndicator;
    @XmlAttribute(name = "NullValueIndicator")
    protected String nullValueIndicator;
    @XmlAttribute(name = "NoDataSerializerIndicator")
    protected String noDataSerializerIndicator;
    @XmlAttribute(name = "TreatNoSuchColumnAsNull")
    protected Boolean treatNoSuchColumnAsNull;
    @XmlAttribute(name = "TreatEmptyAsNull")
    protected Boolean treatEmptyAsNull;
    @XmlAttribute(name = "NullIsTypeless")
    protected Boolean nullIsTypeless;
    @XmlAttribute(name = "scope")
    protected String scope;
    @XmlAttribute(name = "numberOfHashFiles")
    protected Integer numberOfHashFiles;
    @XmlAttribute(name = "NestedElementSepator")
    protected String nestedElementSepator;

    /**
     * Gets the value of the sourceDbOrSourcePrepared property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceDbOrSourcePrepared property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceDbOrSourcePrepared().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Config.SourceDb }
     * {@link Config.SourcePrepared }
     * 
     * 
     */
    public List<Object> getSourceDbOrSourcePrepared() {
        if (sourceDbOrSourcePrepared == null) {
            sourceDbOrSourcePrepared = new ArrayList<Object>();
        }
        return this.sourceDbOrSourcePrepared;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        if (action == null) {
            return "COMPARE";
        } else {
            return action;
        }
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the groupByKey property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGroupByKey() {
        if (groupByKey == null) {
            return false;
        } else {
            return groupByKey;
        }
    }

    /**
     * Sets the value of the groupByKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGroupByKey(Boolean value) {
        this.groupByKey = value;
    }

    /**
     * Gets the value of the displayCheckSum property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDisplayCheckSum() {
        if (displayCheckSum == null) {
            return false;
        } else {
            return displayCheckSum;
        }
    }

    /**
     * Sets the value of the displayCheckSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayCheckSum(Boolean value) {
        this.displayCheckSum = value;
    }

    /**
     * Gets the value of the idCharset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdCharset() {
        if (idCharset == null) {
            return "ISO-8859-15";
        } else {
            return idCharset;
        }
    }

    /**
     * Sets the value of the idCharset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdCharset(String value) {
        this.idCharset = value;
    }

    /**
     * Gets the value of the dateFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFormat() {
        if (dateFormat == null) {
            return "dd.MM.yyyy";
        } else {
            return dateFormat;
        }
    }

    /**
     * Sets the value of the dateFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFormat(String value) {
        this.dateFormat = value;
    }

    /**
     * Gets the value of the timestampFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimestampFormat() {
        if (timestampFormat == null) {
            return "dd.MM.yyyy HH:mm:ss.SSSSSSSSS";
        } else {
            return timestampFormat;
        }
    }

    /**
     * Sets the value of the timestampFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestampFormat(String value) {
        this.timestampFormat = value;
    }

    /**
     * Gets the value of the timeFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeFormat() {
        if (timeFormat == null) {
            return "HH:mm:ss.SSSSSSSSS";
        } else {
            return timeFormat;
        }
    }

    /**
     * Sets the value of the timeFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeFormat(String value) {
        this.timeFormat = value;
    }

    /**
     * Gets the value of the rows property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getRows() {
        if (rows == null) {
            return  1000000L;
        } else {
            return rows;
        }
    }

    /**
     * Sets the value of the rows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRows(Long value) {
        this.rows = value;
    }

    /**
     * Gets the value of the loggedMismatchesMax property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getLoggedMismatchesMax() {
        if (loggedMismatchesMax == null) {
            return  9223372036854775807L;
        } else {
            return loggedMismatchesMax;
        }
    }

    /**
     * Sets the value of the loggedMismatchesMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLoggedMismatchesMax(Long value) {
        this.loggedMismatchesMax = value;
    }

    /**
     * Gets the value of the maxKeyColSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxKeyColSize() {
        if (maxKeyColSize == null) {
            return  255;
        } else {
            return maxKeyColSize;
        }
    }

    /**
     * Sets the value of the maxKeyColSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxKeyColSize(Integer value) {
        this.maxKeyColSize = value;
    }

    /**
     * Gets the value of the hashMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHashMethod() {
        if (hashMethod == null) {
            return "MD5";
        } else {
            return hashMethod;
        }
    }

    /**
     * Sets the value of the hashMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHashMethod(String value) {
        this.hashMethod = value;
    }

    /**
     * Gets the value of the queueChunkSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getQueueChunkSize() {
        if (queueChunkSize == null) {
            return  1000;
        } else {
            return queueChunkSize;
        }
    }

    /**
     * Sets the value of the queueChunkSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQueueChunkSize(Integer value) {
        this.queueChunkSize = value;
    }

    /**
     * Gets the value of the parallelDegree property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getParallelDegree() {
        if (parallelDegree == null) {
            return  8;
        } else {
            return parallelDegree;
        }
    }

    /**
     * Sets the value of the parallelDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParallelDegree(Integer value) {
        this.parallelDegree = value;
    }

    /**
     * Gets the value of the hashBuilderQueueSizePerSource property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getHashBuilderQueueSizePerSource() {
        if (hashBuilderQueueSizePerSource == null) {
            return  2;
        } else {
            return hashBuilderQueueSizePerSource;
        }
    }

    /**
     * Sets the value of the hashBuilderQueueSizePerSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHashBuilderQueueSizePerSource(Integer value) {
        this.hashBuilderQueueSizePerSource = value;
    }

    /**
     * Gets the value of the logColumnSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogColumnSeparator() {
        if (logColumnSeparator == null) {
            return ";";
        } else {
            return logColumnSeparator;
        }
    }

    /**
     * Sets the value of the logColumnSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogColumnSeparator(String value) {
        this.logColumnSeparator = value;
    }

    /**
     * Gets the value of the logKeyValueSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogKeyValueSeparator() {
        if (logKeyValueSeparator == null) {
            return ",";
        } else {
            return logKeyValueSeparator;
        }
    }

    /**
     * Sets the value of the logKeyValueSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogKeyValueSeparator(String value) {
        this.logKeyValueSeparator = value;
    }

    /**
     * Gets the value of the logKeyValueEnclosedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogKeyValueEnclosedBy() {
        if (logKeyValueEnclosedBy == null) {
            return "\"";
        } else {
            return logKeyValueEnclosedBy;
        }
    }

    /**
     * Sets the value of the logKeyValueEnclosedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogKeyValueEnclosedBy(String value) {
        this.logKeyValueEnclosedBy = value;
    }

    /**
     * Gets the value of the logPrintHeader property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLogPrintHeader() {
        if (logPrintHeader == null) {
            return true;
        } else {
            return logPrintHeader;
        }
    }

    /**
     * Sets the value of the logPrintHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLogPrintHeader(Boolean value) {
        this.logPrintHeader = value;
    }

    /**
     * Gets the value of the overallColumnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverallColumnName() {
        if (overallColumnName == null) {
            return "THE_REST_OF_THE_COLUMNS";
        } else {
            return overallColumnName;
        }
    }

    /**
     * Sets the value of the overallColumnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverallColumnName(String value) {
        this.overallColumnName = value;
    }

    /**
     * Gets the value of the noSuchColumnIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoSuchColumnIndicator() {
        if (noSuchColumnIndicator == null) {
            return "_NSC_";
        } else {
            return noSuchColumnIndicator;
        }
    }

    /**
     * Sets the value of the noSuchColumnIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoSuchColumnIndicator(String value) {
        this.noSuchColumnIndicator = value;
    }

    /**
     * Gets the value of the nullValueIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNullValueIndicator() {
        if (nullValueIndicator == null) {
            return "_NULL_";
        } else {
            return nullValueIndicator;
        }
    }

    /**
     * Sets the value of the nullValueIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNullValueIndicator(String value) {
        this.nullValueIndicator = value;
    }

    /**
     * Gets the value of the noDataSerializerIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoDataSerializerIndicator() {
        if (noDataSerializerIndicator == null) {
            return "_NDS_";
        } else {
            return noDataSerializerIndicator;
        }
    }

    /**
     * Sets the value of the noDataSerializerIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoDataSerializerIndicator(String value) {
        this.noDataSerializerIndicator = value;
    }

    /**
     * Gets the value of the treatNoSuchColumnAsNull property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTreatNoSuchColumnAsNull() {
        if (treatNoSuchColumnAsNull == null) {
            return false;
        } else {
            return treatNoSuchColumnAsNull;
        }
    }

    /**
     * Sets the value of the treatNoSuchColumnAsNull property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTreatNoSuchColumnAsNull(Boolean value) {
        this.treatNoSuchColumnAsNull = value;
    }

    /**
     * Gets the value of the treatEmptyAsNull property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTreatEmptyAsNull() {
        if (treatEmptyAsNull == null) {
            return false;
        } else {
            return treatEmptyAsNull;
        }
    }

    /**
     * Sets the value of the treatEmptyAsNull property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTreatEmptyAsNull(Boolean value) {
        this.treatEmptyAsNull = value;
    }

    /**
     * Gets the value of the nullIsTypeless property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNullIsTypeless() {
        if (nullIsTypeless == null) {
            return true;
        } else {
            return nullIsTypeless;
        }
    }

    /**
     * Sets the value of the nullIsTypeless property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNullIsTypeless(Boolean value) {
        this.nullIsTypeless = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        if (scope == null) {
            return "SCHEMA_SELECTED";
        } else {
            return scope;
        }
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

    /**
     * Gets the value of the numberOfHashFiles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfHashFiles() {
        return numberOfHashFiles;
    }

    /**
     * Sets the value of the numberOfHashFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfHashFiles(Integer value) {
        this.numberOfHashFiles = value;
    }

    /**
     * Gets the value of the nestedElementSepator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNestedElementSepator() {
        if (nestedElementSepator == null) {
            return ".";
        } else {
            return nestedElementSepator;
        }
    }

    /**
     * Sets the value of the nestedElementSepator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNestedElementSepator(String value) {
        this.nestedElementSepator = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="table" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="query" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="column" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="nameFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                           &lt;attribute name="secondaryKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                           &lt;attribute name="compare" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="nameFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="schemaFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="rows" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
     *                 &lt;attribute name="compare" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *                 &lt;attribute name="groupByKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
     *       &lt;attribute name="connectionUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="schema" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="preferredKey" default="PK">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="ROWID"/>
     *             &lt;enumeration value="PK"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "table"
    })
    public static class SourceDb {

        protected List<Config.SourceDb.Table> table;
        @XmlAttribute(name = "name", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String name;
        @XmlAttribute(name = "connectionUrl", required = true)
        protected String connectionUrl;
        @XmlAttribute(name = "schema")
        protected String schema;
        @XmlAttribute(name = "preferredKey")
        protected String preferredKey;

        /**
         * Gets the value of the table property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the table property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTable().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Config.SourceDb.Table }
         * 
         * 
         */
        public List<Config.SourceDb.Table> getTable() {
            if (table == null) {
                table = new ArrayList<Config.SourceDb.Table>();
            }
            return this.table;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the connectionUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConnectionUrl() {
            return connectionUrl;
        }

        /**
         * Sets the value of the connectionUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConnectionUrl(String value) {
            this.connectionUrl = value;
        }

        /**
         * Gets the value of the schema property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSchema() {
            return schema;
        }

        /**
         * Sets the value of the schema property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSchema(String value) {
            this.schema = value;
        }

        /**
         * Gets the value of the preferredKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreferredKey() {
            if (preferredKey == null) {
                return "PK";
            } else {
                return preferredKey;
            }
        }

        /**
         * Sets the value of the preferredKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreferredKey(String value) {
            this.preferredKey = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="query" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="column" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="nameFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                 &lt;attribute name="secondaryKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                 &lt;attribute name="compare" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="nameFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="schemaFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="rows" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
         *       &lt;attribute name="compare" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
         *       &lt;attribute name="groupByKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "query",
            "column"
        })
        public static class Table {

            protected String query;
            protected List<Config.SourceDb.Table.Column> column;
            @XmlAttribute(name = "nameFilter")
            protected String nameFilter;
            @XmlAttribute(name = "schemaFilter")
            protected String schemaFilter;
            @XmlAttribute(name = "alias")
            protected String alias;
            @XmlAttribute(name = "rows")
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger rows;
            @XmlAttribute(name = "compare")
            protected Boolean compare;
            @XmlAttribute(name = "groupByKey")
            protected Boolean groupByKey;

            /**
             * Gets the value of the query property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuery() {
                return query;
            }

            /**
             * Sets the value of the query property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuery(String value) {
                this.query = value;
            }

            /**
             * Gets the value of the column property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the column property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getColumn().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Config.SourceDb.Table.Column }
             * 
             * 
             */
            public List<Config.SourceDb.Table.Column> getColumn() {
                if (column == null) {
                    column = new ArrayList<Config.SourceDb.Table.Column>();
                }
                return this.column;
            }

            /**
             * Gets the value of the nameFilter property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNameFilter() {
                return nameFilter;
            }

            /**
             * Sets the value of the nameFilter property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNameFilter(String value) {
                this.nameFilter = value;
            }

            /**
             * Gets the value of the schemaFilter property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSchemaFilter() {
                return schemaFilter;
            }

            /**
             * Sets the value of the schemaFilter property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSchemaFilter(String value) {
                this.schemaFilter = value;
            }

            /**
             * Gets the value of the alias property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAlias() {
                return alias;
            }

            /**
             * Sets the value of the alias property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAlias(String value) {
                this.alias = value;
            }

            /**
             * Gets the value of the rows property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRows() {
                return rows;
            }

            /**
             * Sets the value of the rows property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRows(BigInteger value) {
                this.rows = value;
            }

            /**
             * Gets the value of the compare property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isCompare() {
                if (compare == null) {
                    return true;
                } else {
                    return compare;
                }
            }

            /**
             * Sets the value of the compare property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setCompare(Boolean value) {
                this.compare = value;
            }

            /**
             * Gets the value of the groupByKey property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isGroupByKey() {
                return groupByKey;
            }

            /**
             * Sets the value of the groupByKey property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setGroupByKey(Boolean value) {
                this.groupByKey = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="nameFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *       &lt;attribute name="secondaryKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *       &lt;attribute name="compare" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Column {

                @XmlAttribute(name = "nameFilter")
                protected String nameFilter;
                @XmlAttribute(name = "alias")
                protected String alias;
                @XmlAttribute(name = "key")
                protected Boolean key;
                @XmlAttribute(name = "secondaryKey")
                protected Boolean secondaryKey;
                @XmlAttribute(name = "compare")
                protected Boolean compare;

                /**
                 * Gets the value of the nameFilter property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNameFilter() {
                    return nameFilter;
                }

                /**
                 * Sets the value of the nameFilter property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNameFilter(String value) {
                    this.nameFilter = value;
                }

                /**
                 * Gets the value of the alias property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAlias() {
                    return alias;
                }

                /**
                 * Sets the value of the alias property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAlias(String value) {
                    this.alias = value;
                }

                /**
                 * Gets the value of the key property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isKey() {
                    return key;
                }

                /**
                 * Sets the value of the key property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setKey(Boolean value) {
                    this.key = value;
                }

                /**
                 * Gets the value of the secondaryKey property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isSecondaryKey() {
                    return secondaryKey;
                }

                /**
                 * Sets the value of the secondaryKey property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setSecondaryKey(Boolean value) {
                    this.secondaryKey = value;
                }

                /**
                 * Gets the value of the compare property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public boolean isCompare() {
                    if (compare == null) {
                        return true;
                    } else {
                        return compare;
                    }
                }

                /**
                 * Sets the value of the compare property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setCompare(Boolean value) {
                    this.compare = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SourcePrepared {

        @XmlAttribute(name = "name", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String name;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
