//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.02 at 09:23:40 PM EET 
//


package mse.difftab.prepared;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mse.difftab.prepared package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mse.difftab.prepared
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Prepared }
     * 
     */
    public Prepared createPrepared() {
        return new Prepared();
    }

    /**
     * Create an instance of {@link Prepared.Table }
     * 
     */
    public Prepared.Table createPreparedTable() {
        return new Prepared.Table();
    }

    /**
     * Create an instance of {@link Prepared.Table.Chunks }
     * 
     */
    public Prepared.Table.Chunks createPreparedTableChunks() {
        return new Prepared.Table.Chunks();
    }

    /**
     * Create an instance of {@link Prepared.Table.Columns }
     * 
     */
    public Prepared.Table.Columns createPreparedTableColumns() {
        return new Prepared.Table.Columns();
    }

    /**
     * Create an instance of {@link Prepared.Table.Chunks.Chunk }
     * 
     */
    public Prepared.Table.Chunks.Chunk createPreparedTableChunksChunk() {
        return new Prepared.Table.Chunks.Chunk();
    }

    /**
     * Create an instance of {@link Prepared.Table.Columns.Column }
     * 
     */
    public Prepared.Table.Columns.Column createPreparedTableColumnsColumn() {
        return new Prepared.Table.Columns.Column();
    }

}
