//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 10:26:39 PM EEST 
//


package mse.difftab.prepared;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="table">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="columns">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element name="column">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="jdbcClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="hasherClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="hashIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                                     &lt;attribute name="keyIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="chunks" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element name="chunk">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="fileIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                                     &lt;attribute name="begin" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *                                     &lt;attribute name="end" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="groupByKey" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="rows" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *                 &lt;attribute name="numberOfFiles" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="hashMethod" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="idCharset" type="{http://www.w3.org/2001/XMLSchema}string" default="ISO-8859-15" />
 *       &lt;attribute name="TreatNoSuchColumnAsNull" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="TreatEmptyAsNull" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="NullIsTypeless" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "table"
})
@XmlRootElement(name = "prepared")
public class Prepared {

    @XmlElement(required = true)
    protected List<Prepared.Table> table;
    @XmlAttribute(name = "hashMethod", required = true)
    protected String hashMethod;
    @XmlAttribute(name = "idCharset")
    protected String idCharset;
    @XmlAttribute(name = "TreatNoSuchColumnAsNull")
    protected Boolean treatNoSuchColumnAsNull;
    @XmlAttribute(name = "TreatEmptyAsNull")
    protected Boolean treatEmptyAsNull;
    @XmlAttribute(name = "NullIsTypeless")
    protected Boolean nullIsTypeless;

    /**
     * Gets the value of the table property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the table property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Prepared.Table }
     * 
     * 
     */
    public List<Prepared.Table> getTable() {
        if (table == null) {
            table = new ArrayList<Prepared.Table>();
        }
        return this.table;
    }

    /**
     * Gets the value of the hashMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHashMethod() {
        return hashMethod;
    }

    /**
     * Sets the value of the hashMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHashMethod(String value) {
        this.hashMethod = value;
    }

    /**
     * Gets the value of the idCharset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdCharset() {
        if (idCharset == null) {
            return "ISO-8859-15";
        } else {
            return idCharset;
        }
    }

    /**
     * Sets the value of the idCharset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdCharset(String value) {
        this.idCharset = value;
    }

    /**
     * Gets the value of the treatNoSuchColumnAsNull property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTreatNoSuchColumnAsNull() {
        if (treatNoSuchColumnAsNull == null) {
            return false;
        } else {
            return treatNoSuchColumnAsNull;
        }
    }

    /**
     * Sets the value of the treatNoSuchColumnAsNull property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTreatNoSuchColumnAsNull(Boolean value) {
        this.treatNoSuchColumnAsNull = value;
    }

    /**
     * Gets the value of the treatEmptyAsNull property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTreatEmptyAsNull() {
        if (treatEmptyAsNull == null) {
            return false;
        } else {
            return treatEmptyAsNull;
        }
    }

    /**
     * Sets the value of the treatEmptyAsNull property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTreatEmptyAsNull(Boolean value) {
        this.treatEmptyAsNull = value;
    }

    /**
     * Gets the value of the nullIsTypeless property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNullIsTypeless() {
        if (nullIsTypeless == null) {
            return true;
        } else {
            return nullIsTypeless;
        }
    }

    /**
     * Sets the value of the nullIsTypeless property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNullIsTypeless(Boolean value) {
        this.nullIsTypeless = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="columns">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="column">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="jdbcClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="hasherClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="hashIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                           &lt;attribute name="keyIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="chunks" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="chunk">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="fileIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                           &lt;attribute name="begin" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
     *                           &lt;attribute name="end" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="groupByKey" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="rows" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
     *       &lt;attribute name="numberOfFiles" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "columns",
        "chunks"
    })
    public static class Table {

        @XmlElement(required = true)
        protected Prepared.Table.Columns columns;
        protected Prepared.Table.Chunks chunks;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "alias", required = true)
        protected String alias;
        @XmlAttribute(name = "groupByKey", required = true)
        protected boolean groupByKey;
        @XmlAttribute(name = "rows", required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger rows;
        @XmlAttribute(name = "numberOfFiles", required = true)
        @XmlSchemaType(name = "unsignedInt")
        protected long numberOfFiles;

        /**
         * Gets the value of the columns property.
         * 
         * @return
         *     possible object is
         *     {@link Prepared.Table.Columns }
         *     
         */
        public Prepared.Table.Columns getColumns() {
            return columns;
        }

        /**
         * Sets the value of the columns property.
         * 
         * @param value
         *     allowed object is
         *     {@link Prepared.Table.Columns }
         *     
         */
        public void setColumns(Prepared.Table.Columns value) {
            this.columns = value;
        }

        /**
         * Gets the value of the chunks property.
         * 
         * @return
         *     possible object is
         *     {@link Prepared.Table.Chunks }
         *     
         */
        public Prepared.Table.Chunks getChunks() {
            return chunks;
        }

        /**
         * Sets the value of the chunks property.
         * 
         * @param value
         *     allowed object is
         *     {@link Prepared.Table.Chunks }
         *     
         */
        public void setChunks(Prepared.Table.Chunks value) {
            this.chunks = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the alias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlias() {
            return alias;
        }

        /**
         * Sets the value of the alias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlias(String value) {
            this.alias = value;
        }

        /**
         * Gets the value of the groupByKey property.
         * 
         */
        public boolean isGroupByKey() {
            return groupByKey;
        }

        /**
         * Sets the value of the groupByKey property.
         * 
         */
        public void setGroupByKey(boolean value) {
            this.groupByKey = value;
        }

        /**
         * Gets the value of the rows property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRows() {
            return rows;
        }

        /**
         * Sets the value of the rows property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRows(BigInteger value) {
            this.rows = value;
        }

        /**
         * Gets the value of the numberOfFiles property.
         * 
         */
        public long getNumberOfFiles() {
            return numberOfFiles;
        }

        /**
         * Sets the value of the numberOfFiles property.
         * 
         */
        public void setNumberOfFiles(long value) {
            this.numberOfFiles = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="chunk">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="fileIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *                 &lt;attribute name="begin" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
         *                 &lt;attribute name="end" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "chunk"
        })
        public static class Chunks {

            @XmlElement(required = true)
            protected List<Prepared.Table.Chunks.Chunk> chunk;

            /**
             * Gets the value of the chunk property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the chunk property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getChunk().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Prepared.Table.Chunks.Chunk }
             * 
             * 
             */
            public List<Prepared.Table.Chunks.Chunk> getChunk() {
                if (chunk == null) {
                    chunk = new ArrayList<Prepared.Table.Chunks.Chunk>();
                }
                return this.chunk;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="fileIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
             *       &lt;attribute name="begin" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
             *       &lt;attribute name="end" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Chunk {

                @XmlAttribute(name = "fileIdx", required = true)
                @XmlSchemaType(name = "unsignedInt")
                protected long fileIdx;
                @XmlAttribute(name = "begin", required = true)
                @XmlSchemaType(name = "unsignedLong")
                protected BigInteger begin;
                @XmlAttribute(name = "end", required = true)
                @XmlSchemaType(name = "unsignedLong")
                protected BigInteger end;

                /**
                 * Gets the value of the fileIdx property.
                 * 
                 */
                public long getFileIdx() {
                    return fileIdx;
                }

                /**
                 * Sets the value of the fileIdx property.
                 * 
                 */
                public void setFileIdx(long value) {
                    this.fileIdx = value;
                }

                /**
                 * Gets the value of the begin property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getBegin() {
                    return begin;
                }

                /**
                 * Sets the value of the begin property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setBegin(BigInteger value) {
                    this.begin = value;
                }

                /**
                 * Gets the value of the end property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getEnd() {
                    return end;
                }

                /**
                 * Sets the value of the end property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setEnd(BigInteger value) {
                    this.end = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="column">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="jdbcClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="hasherClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="hashIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *                 &lt;attribute name="keyIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "column"
        })
        public static class Columns {

            @XmlElement(required = true)
            protected List<Prepared.Table.Columns.Column> column;

            /**
             * Gets the value of the column property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the column property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getColumn().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Prepared.Table.Columns.Column }
             * 
             * 
             */
            public List<Prepared.Table.Columns.Column> getColumn() {
                if (column == null) {
                    column = new ArrayList<Prepared.Table.Columns.Column>();
                }
                return this.column;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="jdbcClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="hasherClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="hashIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
             *       &lt;attribute name="keyIdx" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Column {

                @XmlAttribute(name = "name", required = true)
                protected String name;
                @XmlAttribute(name = "alias", required = true)
                protected String alias;
                @XmlAttribute(name = "jdbcClassName", required = true)
                protected String jdbcClassName;
                @XmlAttribute(name = "hasherClassName", required = true)
                protected String hasherClassName;
                @XmlAttribute(name = "hashIdx", required = true)
                @XmlSchemaType(name = "unsignedInt")
                protected long hashIdx;
                @XmlAttribute(name = "keyIdx", required = true)
                @XmlSchemaType(name = "unsignedInt")
                protected long keyIdx;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the alias property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAlias() {
                    return alias;
                }

                /**
                 * Sets the value of the alias property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAlias(String value) {
                    this.alias = value;
                }

                /**
                 * Gets the value of the jdbcClassName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getJdbcClassName() {
                    return jdbcClassName;
                }

                /**
                 * Sets the value of the jdbcClassName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setJdbcClassName(String value) {
                    this.jdbcClassName = value;
                }

                /**
                 * Gets the value of the hasherClassName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHasherClassName() {
                    return hasherClassName;
                }

                /**
                 * Sets the value of the hasherClassName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHasherClassName(String value) {
                    this.hasherClassName = value;
                }

                /**
                 * Gets the value of the hashIdx property.
                 * 
                 */
                public long getHashIdx() {
                    return hashIdx;
                }

                /**
                 * Sets the value of the hashIdx property.
                 * 
                 */
                public void setHashIdx(long value) {
                    this.hashIdx = value;
                }

                /**
                 * Gets the value of the keyIdx property.
                 * 
                 */
                public long getKeyIdx() {
                    return keyIdx;
                }

                /**
                 * Sets the value of the keyIdx property.
                 * 
                 */
                public void setKeyIdx(long value) {
                    this.keyIdx = value;
                }

            }

        }

    }

}
